# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'y:\STUDY PHD\TERM 4 - PHD\Coursera\Learn OpenCV\OpenCV 1\GUI\QT\Python\PyQT\examples\Color picker_CHOICE\slickpicker-master\chromkey_mainWindow_xml.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(590, 240, 431, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.color_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.color_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.color_horizontalLayout.setObjectName("color_horizontalLayout")
        self.textColorCode = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.textColorCode.setReadOnly(True)
        self.textColorCode.setObjectName("textColorCode")
        self.color_horizontalLayout.addWidget(self.textColorCode)
        self.buttonPickScreen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonPickScreen.setObjectName("buttonPickScreen")
        self.color_horizontalLayout.addWidget(self.buttonPickScreen)
        self.buttonColorPalette = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonColorPalette.setObjectName("buttonColorPalette")
        self.color_horizontalLayout.addWidget(self.buttonColorPalette)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 561, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.video_mainVBoxLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.video_mainVBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video_mainVBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.video_mainVBoxLayout.setObjectName("video_mainVBoxLayout")
        self.video_labelInput = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_labelInput.sizePolicy().hasHeightForWidth())
        self.video_labelInput.setSizePolicy(sizePolicy)
        self.video_labelInput.setObjectName("video_labelInput")
        self.video_mainVBoxLayout.addWidget(self.video_labelInput)
        self.video_displayWidget = QVideoWidget(self.verticalLayoutWidget)
        self.video_displayWidget.setObjectName("video_displayWidget")
        self.video_mainVBoxLayout.addWidget(self.video_displayWidget)
        self.video_toolHBoxLayout = QtWidgets.QHBoxLayout()
        self.video_toolHBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.video_toolHBoxLayout.setObjectName("video_toolHBoxLayout")
        self.video_buttonOpen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.video_buttonOpen.setObjectName("video_buttonOpen")
        self.video_toolHBoxLayout.addWidget(self.video_buttonOpen)
        self.video_buttonPlay = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.video_buttonPlay.setEnabled(True)
        self.video_buttonPlay.setObjectName("video_buttonPlay")
        self.video_toolHBoxLayout.addWidget(self.video_buttonPlay)
        self.video_labelCurrent = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_labelCurrent.sizePolicy().hasHeightForWidth())
        self.video_labelCurrent.setSizePolicy(sizePolicy)
        self.video_labelCurrent.setObjectName("video_labelCurrent")
        self.video_toolHBoxLayout.addWidget(self.video_labelCurrent)
        self.video_hSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.video_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.video_hSlider.setObjectName("video_hSlider")
        self.video_toolHBoxLayout.addWidget(self.video_hSlider)
        self.video_labelTotal = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_labelTotal.sizePolicy().hasHeightForWidth())
        self.video_labelTotal.setSizePolicy(sizePolicy)
        self.video_labelTotal.setText("")
        self.video_labelTotal.setObjectName("video_labelTotal")
        self.video_toolHBoxLayout.addWidget(self.video_labelTotal)
        self.video_mainVBoxLayout.addLayout(self.video_toolHBoxLayout)
        self.video_labelStatus = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_labelStatus.sizePolicy().hasHeightForWidth())
        self.video_labelStatus.setSizePolicy(sizePolicy)
        self.video_labelStatus.setObjectName("video_labelStatus")
        self.video_mainVBoxLayout.addWidget(self.video_labelStatus)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(590, 300, 431, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.edit_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.edit_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.edit_gridLayout.setObjectName("edit_gridLayout")
        self.edit_labelTolValue = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_labelTolValue.sizePolicy().hasHeightForWidth())
        self.edit_labelTolValue.setSizePolicy(sizePolicy)
        self.edit_labelTolValue.setObjectName("edit_labelTolValue")
        self.edit_gridLayout.addWidget(self.edit_labelTolValue, 0, 2, 1, 1)
        self.edit_labelTol = QtWidgets.QLabel(self.gridLayoutWidget)
        self.edit_labelTol.setObjectName("edit_labelTol")
        self.edit_gridLayout.addWidget(self.edit_labelTol, 0, 0, 1, 1)
        self.edit_hSliderDefringe = QtWidgets.QSlider(self.gridLayoutWidget)
        self.edit_hSliderDefringe.setMaximum(100)
        self.edit_hSliderDefringe.setOrientation(QtCore.Qt.Horizontal)
        self.edit_hSliderDefringe.setObjectName("edit_hSliderDefringe")
        self.edit_gridLayout.addWidget(self.edit_hSliderDefringe, 2, 1, 1, 1)
        self.edit_labelDefringe = QtWidgets.QLabel(self.gridLayoutWidget)
        self.edit_labelDefringe.setObjectName("edit_labelDefringe")
        self.edit_gridLayout.addWidget(self.edit_labelDefringe, 2, 0, 1, 1)
        self.edit_hSliderTol = QtWidgets.QSlider(self.gridLayoutWidget)
        self.edit_hSliderTol.setMaximum(100)
        self.edit_hSliderTol.setOrientation(QtCore.Qt.Horizontal)
        self.edit_hSliderTol.setObjectName("edit_hSliderTol")
        self.edit_gridLayout.addWidget(self.edit_hSliderTol, 0, 1, 1, 1)
        self.edit_labelSoftValue = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_labelSoftValue.sizePolicy().hasHeightForWidth())
        self.edit_labelSoftValue.setSizePolicy(sizePolicy)
        self.edit_labelSoftValue.setObjectName("edit_labelSoftValue")
        self.edit_gridLayout.addWidget(self.edit_labelSoftValue, 1, 2, 1, 1)
        self.edit_labelSoft = QtWidgets.QLabel(self.gridLayoutWidget)
        self.edit_labelSoft.setObjectName("edit_labelSoft")
        self.edit_gridLayout.addWidget(self.edit_labelSoft, 1, 0, 1, 1)
        self.edit_hSliderSoft = QtWidgets.QSlider(self.gridLayoutWidget)
        self.edit_hSliderSoft.setMaximum(100)
        self.edit_hSliderSoft.setOrientation(QtCore.Qt.Horizontal)
        self.edit_hSliderSoft.setObjectName("edit_hSliderSoft")
        self.edit_gridLayout.addWidget(self.edit_hSliderSoft, 1, 1, 1, 1)
        self.edit_labelDefringeValue = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_labelDefringeValue.sizePolicy().hasHeightForWidth())
        self.edit_labelDefringeValue.setSizePolicy(sizePolicy)
        self.edit_labelDefringeValue.setObjectName("edit_labelDefringeValue")
        self.edit_gridLayout.addWidget(self.edit_labelDefringeValue, 2, 2, 1, 1)
        self.edit_buttonSave = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_buttonSave.sizePolicy().hasHeightForWidth())
        self.edit_buttonSave.setSizePolicy(sizePolicy)
        self.edit_buttonSave.setObjectName("edit_buttonSave")
        self.edit_gridLayout.addWidget(self.edit_buttonSave, 3, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(590, 10, 351, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.video_outputLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.video_outputLayout.setContentsMargins(0, 0, 0, 0)
        self.video_outputLayout.setObjectName("video_outputLayout")
        self.video_labelOutput = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_labelOutput.sizePolicy().hasHeightForWidth())
        self.video_labelOutput.setSizePolicy(sizePolicy)
        self.video_labelOutput.setObjectName("video_labelOutput")
        self.video_outputLayout.addWidget(self.video_labelOutput)
        self.video_outputFrame = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.video_outputFrame.setText("")
        self.video_outputFrame.setObjectName("video_outputFrame")
        self.video_outputLayout.addWidget(self.video_outputFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPickScreen.setText(_translate("MainWindow", "Pick Color"))
        self.buttonColorPalette.setText(_translate("MainWindow", "Color Palette"))
        self.video_labelInput.setText(_translate("MainWindow", "Input Video"))
        self.video_buttonOpen.setText(_translate("MainWindow", "Open"))
        self.video_buttonPlay.setText(_translate("MainWindow", "Play"))
        self.video_labelCurrent.setText(_translate("MainWindow", "0:00"))
        self.video_labelStatus.setText(_translate("MainWindow", "Status"))
        self.edit_labelTolValue.setText(_translate("MainWindow", "    0 %"))
        self.edit_labelTol.setText(_translate("MainWindow", "Tolerance"))
        self.edit_labelDefringe.setText(_translate("MainWindow", "Defringe"))
        self.edit_labelSoftValue.setText(_translate("MainWindow", "    0 %"))
        self.edit_labelSoft.setText(_translate("MainWindow", "Softness"))
        self.edit_labelDefringeValue.setText(_translate("MainWindow", "    0 %"))
        self.edit_buttonSave.setText(_translate("MainWindow", "Save"))
        self.video_labelOutput.setText(_translate("MainWindow", "Output Video"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
